# Exercise 4

In [1]:
import numpy as np

### Soal 1

1. create a null vector / 1D array of size 10 and update fifth value to 11.

In [3]:
a = np.array ([1,2,3,4,5,6,7,8,9,10])
a.size

10

In [5]:
a[5] = 11
print (a)

[ 1  2  3  4  5 11  7  8  9 10]


#### Soal 2

2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

In [6]:
b = np.array ([[1,2,3], [4,5,6]])
print (b)

[[1 2 3]
 [4 5 6]]


In [9]:
b.shape

(2, 3)

In [7]:
c = b.reshape (3,2)
print (c)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
c.shape

(3, 2)

### Soal 3

3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [24]:
my_arr = np.ones([5,5])
print (my_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
my_arr[1:4,1:4] = 0
print (my_arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Soal 4

4. Take a look at the following matrix. Access the [2, 1,1]

In [27]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])

In [28]:
z[2, 1, 1:]

array([2, 9])

# Assignment

### Soal 1

1. Create a 4x4 matrix with values ranging from 0 to 3.\
(The following image is just as an example. It doesn't represent the real image of arrays in the question)

In [45]:
a1 = np.zeros ([4,4])
print (a1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [56]:
a1 [0:4,1] = 1
a1 [0:4,2] = 2
a1 [0:4,3] = 3
print (a1)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


### Soal 2

2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.

In [57]:
b1 = np.array ([[0,1,2,5], [5,3,7,4], [9,8,4,5], [2,8,3,5]])
print (b1)

[[0 1 2 5]
 [5 3 7 4]
 [9 8 4 5]
 [2 8 3 5]]


In [62]:
c1 = np.hsplit (b1, 2)
c1

[array([[0, 1],
        [5, 3],
        [9, 8],
        [2, 8]]),
 array([[2, 5],
        [7, 4],
        [4, 5],
        [3, 5]])]